### PR TITLE
Only provision when necessary (boot2docker is getting these packages)

### PR DESCRIPTION
**Pull request by bshelton229**
The rsync, attr, and acl packages are going to be included in the next boot2docker release. https://github.com/boot2docker/boot2docker/pull/1103

### CODE REVIEW

**Comment by mattes** [comment]
What is the cost of provisioning? `tce-load` should only install if rsync isn't installed, so we could skip the `needsProvisioning` call?

**Comment by dpintats** [comment]
I've tested creating a new virtualbox docker-machine using boot2docker iso 1.10 and manually executing `tce-load -wi rsync attr acl`, and tce does in fact install rsync and attr modules, even though they are already installed. I think the proposed change addresses the situation where one user may have an older version of boot2docker or an up to date version. I also compiled and tested this change and it worked fine.

**Comment by mattes** [comment]
not merging this for now to make sure to always have all the required packages installed.

**Comment by dpintats** [comment]
It's a bummer that this couldn't be merged, because a failure on the tcz repo prevents getting docker-rsync to work, even for up to date boot2docker versions >= 1.10 https://github.com/boot2docker/boot2docker/releases/tag/v1.10.0 and https://github.com/boot2docker/boot2docker/pull/1103 😢

So, I get this kinda thing if I simulate a downed repo by blocking the address in my firewall:
```
Boot2Docker version 1.10.0, build master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
Docker version 1.10.0, build 590d5108
docker@dev3:~$ which rsync
/usr/local/bin/rsync
docker@dev3:~$ tce-load -wi rsync
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: server returned error: HTTP/1.1 503 Service Unavailable
md5sum: rsync.tcz.md5.txt: No such file or directory
Error on rsync.tcz
``` 

Is there any possible alternatives to help get something like this PR merged, without asking developers to alter the tinycore linux mirror list?

**Comment by mattes** [comment]
Ok, you're right @dpintats . There are some merge conflicts now. Do you want to look into this?

**Comment by dpintats** [comment]
You got it, will update shortly

**Comment by dpintats** [comment]
@mattes opened a new PR at https://github.com/synack/docker-rsync/pull/22 to resolve the merge conflicts in @bshelton229 's fork

**Pull request merged**
